export const ActionTypes = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT: "LOGOUT",
    USERS: "USERS",
    DELETEUSER: "DELETEUSER",
    POST : "POST",
    POSTS : "POSTS",
    DELETEPOST : "DELETEPOST",
    COMMENTS: "COMMENTS",
    DELETECOMMENT: "DELETECOMMENT"
}